/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ke_zhu_camera_simple_JniUtils */

#ifndef _Included_com_ke_zhu_camera_simple_JniUtils
#define _Included_com_ke_zhu_camera_simple_JniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ke_zhu_camera_simple_JniUtils
 * Method:    nv21ToI420
 * Signature: ([BII[B)V
 */
JNIEXPORT void JNICALL Java_com_ke_zhu_camera_1simple_JniUtils_nv21ToI420
  (JNIEnv *, jclass, jbyteArray, jint, jint, jbyteArray);

/*
 * Class:     com_ke_zhu_camera_simple_JniUtils
 * Method:    compressYUV
 * Signature: ([BII[BIIIIZ)V
 */
JNIEXPORT void JNICALL Java_com_ke_zhu_camera_1simple_JniUtils_compressYUV
  (JNIEnv *, jclass, jbyteArray, jint, jint, jbyteArray, jint, jint, jint, jint, jboolean);

/*
 * Class:     com_ke_zhu_camera_simple_JniUtils
 * Method:    cropYUV
 * Signature: ([BII[BIIII)V
 */
JNIEXPORT void JNICALL Java_com_ke_zhu_camera_1simple_JniUtils_cropYUV
  (JNIEnv *, jclass, jbyteArray, jint, jint, jbyteArray, jint, jint, jint, jint);

/*
 * Class:     com_ke_zhu_camera_simple_JniUtils
 * Method:    yuvI420ToNV21
 * Signature: ([B[BII)V
 */
JNIEXPORT void JNICALL Java_com_ke_zhu_camera_1simple_JniUtils_yuvI420ToNV21
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jint, jint);

/*
 * Class:     com_ke_zhu_camera_simple_JniUtils
 * Method:    scale
 * Signature: ([BII[BII)V
 */
JNIEXPORT void JNICALL Java_com_ke_zhu_camera_1simple_JniUtils_scale
  (JNIEnv *, jclass, jbyteArray, jint, jint, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
